version: 1.0.{build}
os: Visual Studio 2015
configuration: Release
platform: ARM
before_build:
- ps: nuget restore Hastarin.Devices.MCP23S17\Hastarin.Devices.MCP23S17.csproj
build:
  project: Hastarin.Devices.MCP23S17\Hastarin.Devices.MCP23S17.csproj
  verbosity: detailed
after_build:
- ps: nuget pack -Symbols Hastarin.Devices.MCP23S17\Hastarin.Devices.MCP23S17.csproj
artifacts:
- path: '*.nupkg'
deploy:
- provider: NuGet
  api_key:
    secure: qtrhkIpNhyX9c3bqsmu08h35MfZoxamOZ9w/QfovaE2hYFBGaw2R+H6sMJdBe9Bu